[package]
name = "dra"
version = "0.4.8"
edition = "2021"
authors = ["Cosimo Matteini <dev.matteini@gmail.com>"]
description = "A command line tool to download release assets from GitHub"
homepage = "https://github.com/devmatteini/dra"
repository = "https://github.com/devmatteini/dra"
documentation = "https://github.com/devmatteini/dra"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["github", "cli"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
ureq = { version = "2.9.1", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.190", features = ["derive"] }
clap = { version = "4.4.7", features = ["derive"] }
clap_complete = "4.4.4"
dialoguer = "0.11.0"
indicatif = "0.17.7"
uuid = { version = "1.6.1", features = ["v4"] }
ctrlc = "3.4.1"
walkdir = "2.4.0"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
flate2 = { version = "1.0.28", features = ["zlib"] }
tar = "0.4.40"
xz2 = "0.1.7"
bzip2 = "0.4.4"
urlencoding = "2.1.3"

[dev-dependencies]
test-case = "3.3.1"
assert_cmd = "2.0.12"
predicates = "3.0.4"

[package.metadata.deb]
section = "utility"
extended-description = """\
Download Release Assets (dra) is a command line tool
to download release assets from GitHub.
Provides interactive and non-interactive ways to download assets
to meet your needs in different scenarios.
"""
